version: "3.9"

services:
  xsnapster:
    build: .
    image: xsnapster:latest
    container_name: xsnapster_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env 
    volumes:
      - ./logs:/app/logs
